name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags 

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3
      with: 
        submodules: 'true'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        check-latest: true
        cache: 'sbt'
    - name: Run tests
      run: sbt lint test
      env:
        # see https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported
        NODE_OPTIONS: "--openssl-legacy-provider"

  publish:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'release'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          check-latest: true
          cache: 'sbt'
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}